import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/about',
          '/services',
          '/faq',
          '/privacy',
          '/terms',
          '/cookies',
          '/trust-center',
          '/blog',
          '/blog/',
          '/properties',
          '/normal-properties',
          '/premium-properties',
          '/plots',
          '/land',
          '/houses',
          '/investment-reports',
          '/nri-investment',
          '/market-intelligence',
          '/smart-investment',
          '/secure-future',
          '/legacy-wealth',
          '/exponential-growth',
          '/capital-today-tomorrow',
          '/premium-club',
          '/premium',
          '/book-site-visit',
          '/financial-services',
        ],
        disallow: [
          '/dashboard',
          '/owner-portal',
          '/upload',
          '/upload-property',
          '/login',
          '/user-login',
          '/register',
          '/ai-access',
          '/ai-dashboard',
          '/ai-management',
          '/premium-dashboard',
          '/premium',
          '/profile-settings',
          '/onboarding',
          '/offline',
          '/api/',
        ],
      },
    ],
    sitemap: 'https://astrustedconsultancy.com/sitemap.xml',
  };
}
